name: React App Deploy on Surge

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
         version: '20'

    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v5.0.0
      with:
          # Yarn command
          cmd: install

    - name: Creating build
      run: yarn build

    - name: Installing Surge
      run: npm install -g surge
      
    - name: Deploy on surge
      run: surge ./build --domain https://asf-first-app.surge.sh --token ${{secrets.SURGE_TOKEN}}
      
